# Generated by Django 3.0.1 on 2020-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='status',
            field=models.CharField(max_length=1000),
        ),
    ]
